/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ScienceplanImport } from './routes/science_plan'
import { Route as IndexImport } from './routes/index'
import { Route as ScienceplanIndexImport } from './routes/science_plan/index'
import { Route as ScienceplanPlanidImport } from './routes/science_plan/$plan_id'
import { Route as ScienceplanValidateIndexImport } from './routes/science_plan/validate/index'
import { Route as ScienceplanValidatePlanidImport } from './routes/science_plan/validate/$plan_id'

// Create/Update Routes

const ScienceplanRoute = ScienceplanImport.update({
  id: '/science_plan',
  path: '/science_plan',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ScienceplanIndexRoute = ScienceplanIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScienceplanRoute,
} as any)

const ScienceplanPlanidRoute = ScienceplanPlanidImport.update({
  id: '/$plan_id',
  path: '/$plan_id',
  getParentRoute: () => ScienceplanRoute,
} as any)

const ScienceplanValidateIndexRoute = ScienceplanValidateIndexImport.update({
  id: '/validate/',
  path: '/validate/',
  getParentRoute: () => ScienceplanRoute,
} as any)

const ScienceplanValidatePlanidRoute = ScienceplanValidatePlanidImport.update({
  id: '/validate/$plan_id',
  path: '/validate/$plan_id',
  getParentRoute: () => ScienceplanRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/science_plan': {
      id: '/science_plan'
      path: '/science_plan'
      fullPath: '/science_plan'
      preLoaderRoute: typeof ScienceplanImport
      parentRoute: typeof rootRoute
    }
    '/science_plan/$plan_id': {
      id: '/science_plan/$plan_id'
      path: '/$plan_id'
      fullPath: '/science_plan/$plan_id'
      preLoaderRoute: typeof ScienceplanPlanidImport
      parentRoute: typeof ScienceplanImport
    }
    '/science_plan/': {
      id: '/science_plan/'
      path: '/'
      fullPath: '/science_plan/'
      preLoaderRoute: typeof ScienceplanIndexImport
      parentRoute: typeof ScienceplanImport
    }
    '/science_plan/validate/$plan_id': {
      id: '/science_plan/validate/$plan_id'
      path: '/validate/$plan_id'
      fullPath: '/science_plan/validate/$plan_id'
      preLoaderRoute: typeof ScienceplanValidatePlanidImport
      parentRoute: typeof ScienceplanImport
    }
    '/science_plan/validate/': {
      id: '/science_plan/validate/'
      path: '/validate'
      fullPath: '/science_plan/validate'
      preLoaderRoute: typeof ScienceplanValidateIndexImport
      parentRoute: typeof ScienceplanImport
    }
  }
}

// Create and export the route tree

interface ScienceplanRouteChildren {
  ScienceplanPlanidRoute: typeof ScienceplanPlanidRoute
  ScienceplanIndexRoute: typeof ScienceplanIndexRoute
  ScienceplanValidatePlanidRoute: typeof ScienceplanValidatePlanidRoute
  ScienceplanValidateIndexRoute: typeof ScienceplanValidateIndexRoute
}

const ScienceplanRouteChildren: ScienceplanRouteChildren = {
  ScienceplanPlanidRoute: ScienceplanPlanidRoute,
  ScienceplanIndexRoute: ScienceplanIndexRoute,
  ScienceplanValidatePlanidRoute: ScienceplanValidatePlanidRoute,
  ScienceplanValidateIndexRoute: ScienceplanValidateIndexRoute,
}

const ScienceplanRouteWithChildren = ScienceplanRoute._addFileChildren(
  ScienceplanRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/science_plan': typeof ScienceplanRouteWithChildren
  '/science_plan/$plan_id': typeof ScienceplanPlanidRoute
  '/science_plan/': typeof ScienceplanIndexRoute
  '/science_plan/validate/$plan_id': typeof ScienceplanValidatePlanidRoute
  '/science_plan/validate': typeof ScienceplanValidateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/science_plan/$plan_id': typeof ScienceplanPlanidRoute
  '/science_plan': typeof ScienceplanIndexRoute
  '/science_plan/validate/$plan_id': typeof ScienceplanValidatePlanidRoute
  '/science_plan/validate': typeof ScienceplanValidateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/science_plan': typeof ScienceplanRouteWithChildren
  '/science_plan/$plan_id': typeof ScienceplanPlanidRoute
  '/science_plan/': typeof ScienceplanIndexRoute
  '/science_plan/validate/$plan_id': typeof ScienceplanValidatePlanidRoute
  '/science_plan/validate/': typeof ScienceplanValidateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/science_plan'
    | '/science_plan/$plan_id'
    | '/science_plan/'
    | '/science_plan/validate/$plan_id'
    | '/science_plan/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/science_plan/$plan_id'
    | '/science_plan'
    | '/science_plan/validate/$plan_id'
    | '/science_plan/validate'
  id:
    | '__root__'
    | '/'
    | '/science_plan'
    | '/science_plan/$plan_id'
    | '/science_plan/'
    | '/science_plan/validate/$plan_id'
    | '/science_plan/validate/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScienceplanRoute: typeof ScienceplanRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScienceplanRoute: ScienceplanRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/science_plan"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/science_plan": {
      "filePath": "science_plan.tsx",
      "children": [
        "/science_plan/$plan_id",
        "/science_plan/",
        "/science_plan/validate/$plan_id",
        "/science_plan/validate/"
      ]
    },
    "/science_plan/$plan_id": {
      "filePath": "science_plan/$plan_id.tsx",
      "parent": "/science_plan"
    },
    "/science_plan/": {
      "filePath": "science_plan/index.tsx",
      "parent": "/science_plan"
    },
    "/science_plan/validate/$plan_id": {
      "filePath": "science_plan/validate/$plan_id.tsx",
      "parent": "/science_plan"
    },
    "/science_plan/validate/": {
      "filePath": "science_plan/validate/index.tsx",
      "parent": "/science_plan"
    }
  }
}
ROUTE_MANIFEST_END */
